### PR TITLE
feature/transcription-engine

### LINKED ISSUE #11: Hämta transkriberingsförfrågan från kö

### LINKED ISSUE #12: Skapa transkriberingsmotor

### LINKED ISSUE #42: Lägg upp transkribering till databas

### PR DESCRIPTION
**Pull request by ABerger81**

### CODE REVIEW

**Comment by seffradev** [comment]
Database connection and writing to it when a transcription has finished is what is left to implement before this branch leaves the draft stage.

**Review by ABerger81 — COMMENTED** [review]
Can't "Approve"
PR authors can't approve their own PR

**Review by seffradev — DISMISSED** [review]
LGTY

**Review by seffradev — APPROVED** [review]
LGTM

**Pull request merged**
